### ISSUE TITLE
Provide documented examples on how to exercise the system

### ISSUE THREAD

**Issue by bobbrady** [ChemAxon/jchem-webservice-docker#4]
Currently there are no documented examples on how to exercise the system once it is up and running.  For example, providing simple cURL requests to endpoints would be helpful.

Each documented use case should include a description of what API call is being exercised, what the required inputs are, and what the expected out put is.  This doesn't need to cover every API call, just a few samples.

**Comment by bzaicsek-cxn** [comment]
Hi!

   Please find the documentation here: https://docs.chemaxon.com/display/docs/JChem+Web+Services+Classic

and here: https://restdemo.chemaxon.com/apidocs/ This live demo and documentation as also available in the application.
